version: '3.8'

services:
  forecasting-bot:
    image: ghcr.io/your-org/ai-forecasting-bot:latest
    container_name: ai-forecasting-bot-blue
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - METRICS_ENABLED=true
      - HEALTH_CHECK_ENABLED=true
      - DEPLOYMENT_COLOR=blue
    env_file:
      - .env
    ports:
      - '8081:8080'
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config:ro
    networks:
      - forecasting-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  forecasting-network:
    external: true
