global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'forecasting-bot-staging'
    static_configs:
      - targets: ['forecasting-bot:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prometheus-staging'
    static_configs:
      - targets: ['localhost:9090']
