name: CI/CD Pipeline

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run lint
        run: poetry run flake8 src tests
      - name: Run tests
        run: poetry run pytest --cov=src --cov-fail-under=80

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        run: |
          echo "Deploy steps go here"
