name: CI/CD Pipeline

on:
  schedule:
    # Updated from every 30 minutes to every 4 hours for tournament optimization
    # Configurable through environment variables in production workflows
    - cron: '0 */4 * * *'
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      scheduling_frequency_hours:
        description: 'Scheduling frequency in hours'
        required: false
        default: '4'
        type: string

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run lint
        run: poetry run flake8 src tests
      - name: Run tests
        run: poetry run pytest --cov=src --cov-fail-under=80

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        run: |
          echo "Deploy steps go here"
          echo "Scheduling frequency: ${{ github.event.inputs.scheduling_frequency_hours || '4' }} hours"
        env:
          # Tournament scheduling configuration
          SCHEDULING_FREQUENCY_HOURS: ${{ github.event.inputs.scheduling_frequency_hours || vars.SCHEDULING_FREQUENCY_HOURS || '4' }}
          DEADLINE_AWARE_SCHEDULING: ${{ vars.DEADLINE_AWARE_SCHEDULING || 'true' }}
          CRITICAL_PERIOD_FREQUENCY_HOURS: ${{ vars.CRITICAL_PERIOD_FREQUENCY_HOURS || '2' }}
          FINAL_24H_FREQUENCY_HOURS: ${{ vars.FINAL_24H_FREQUENCY_HOURS || '1' }}
          TOURNAMENT_SCOPE: ${{ vars.TOURNAMENT_SCOPE || 'seasonal' }}
