#!/bin/bash

# Script to help set up GitHub secrets for the AI Forecasting Bot
# This script provides instructions for setting up secrets in GitHub

echo "🔐 GitHub Secrets Setup for AI Forecasting Bot"
echo "=============================================="
echo ""

echo "STEP-BY-STEP SETUP INSTRUCTIONS:"
echo "1. Go to your GitHub repository"
echo "2. Navigate to: Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret' for each required secret below"
echo "4. Copy the exact secret name and paste your API key value"
echo ""

echo "📋 REQUIRED SECRETS (must be configured for tournament compliance):"
echo "-------------------------------------------------------------------"
echo "Secret Name: METACULUS_TOKEN"
echo "Description: Your Metaculus API token for accessing tournaments"
echo "How to get: Log into Metaculus → Settings → API → Generate Token"
echo "Value: [Paste your actual Metaculus token here]"
echo ""
echo "Secret Name: OPENROUTER_API_KEY"
echo "Description: Your OpenRouter API key for LLM access"
echo "How to get: Visit https://openrouter.ai → Sign up → API Keys"
echo "Value: [Paste your actual OpenRouter API key here]"
echo ""

echo "📋 OPTIONAL SECRETS (will use fallback if not configured):"
echo "---------------------------------------------------------"
echo "Secret Name: PERPLEXITY_API_KEY"
echo "Description: For enhanced search capabilities"
echo "How to get: Visit https://www.perplexity.ai → API → Get API Key"
echo ""
echo "Secret Name: EXA_API_KEY"
echo "Description: For web search functionality"
echo "How to get: Visit https://exa.ai → Sign up → API Keys"
echo ""
echo "Secret Name: OPENAI_API_KEY"
echo "Description: For OpenAI GPT models"
echo "How to get: Visit https://platform.openai.com → API Keys"
echo ""
echo "Secret Name: ANTHROPIC_API_KEY"
echo "Description: For Claude models"
echo "How to get: Visit https://console.anthropic.com → API Keys"
echo ""
echo "Secret Name: ASKNEWS_CLIENT_ID"
echo "Description: For news search functionality"
echo "How to get: Visit https://asknews.app → API → Client Credentials"
echo ""
echo "Secret Name: ASKNEWS_SECRET"
echo "Description: For news search functionality"
echo "How to get: Visit https://asknews.app → API → Client Credentials"
echo ""

echo "✅ SETUP VERIFICATION:"
echo "---------------------"
echo "After setting up the secrets, you can test the workflows by:"
echo "1. Going to Actions tab in your GitHub repository"
echo "2. Selecting 'Forecast on new AI tournament questions' or 'Forecast on Quarterly Cup'"
echo "3. Clicking 'Run workflow' to test manually"
echo ""

echo "🔄 AUTOMATIC SCHEDULING:"
echo "------------------------"
echo "• Tournament forecasting: Every 4 hours (optimized for budget efficiency)"
echo "• Deadline-aware scheduling: Available for critical periods"
echo "• Manual runs: Available through workflow dispatch"
echo ""

echo "⚠️  IMPORTANT NOTES:"
echo "-------------------"
echo "• Never commit API keys to the repository"
echo "• The .env file is already in .gitignore"
echo "• Optional services will use fallback/dummy values if not configured"
echo "• You can add more API keys later as you get credits for other services"
echo ""

echo "📊 OPTIONAL REPOSITORY VARIABLES (for scheduling customization):"
echo "----------------------------------------------------------------"
echo "Go to: Settings → Secrets and variables → Actions → Variables tab"
echo ""
echo "Variable Name: SCHEDULING_FREQUENCY_HOURS"
echo "Description: Default scheduling frequency in hours"
echo "Default: 4"
echo "Example values: 2, 4, 6, 8"
echo ""
echo "Variable Name: DEADLINE_AWARE_SCHEDULING"
echo "Description: Enable deadline-aware scheduling"
echo "Default: true"
echo "Values: true, false"
echo ""
echo "Variable Name: CRITICAL_PERIOD_FREQUENCY_HOURS"
echo "Description: Frequency during critical periods"
echo "Default: 2"
echo "Example values: 1, 2, 3"
echo ""
echo "Variable Name: FINAL_24H_FREQUENCY_HOURS"
echo "Description: Frequency in final 24 hours before deadline"
echo "Default: 1"
echo "Example values: 1, 2"
echo ""
echo "Variable Name: TOURNAMENT_SCOPE"
echo "Description: Tournament operation scope"
echo "Default: seasonal"
echo "Values: seasonal, daily"
echo ""

echo "🚀 Ready to go! Your workflows are now enabled and will use the configured secrets."
