# Development Environment Configuration
environment: development

# Registry Configuration
registry:
  url: 'ghcr.io'
  namespace: 'tournament-optimization'

# Image Configuration
image:
  name: 'tournament-optimization'
  tag: 'dev-latest'
  pull_policy: 'Always'

# Deployment Configuration
deployment:
  replicas: 1
  strategy: 'RollingUpdate'
  max_unavailable: 0
  max_surge: 1

# Resource Configuration
resources:
  requests:
    cpu: '100m'
    memory: '256Mi'
  limits:
    cpu: '500m'
    memory: '512Mi'

# Service Configuration
service:
  type: 'ClusterIP'
  port: 8000
  target_port: 8000

# Ingress Configuration
ingress:
  enabled: true
  host: 'tournament-optimization-dev.example.com'
  tls: false

# Database Configuration
database:
  host: 'localhost'
  port: 5432
  name: 'tournament_optimization_dev'
  username: 'dev_user'
  ssl_mode: 'disable'
  max_connections: 10
  connection_timeout: 30

# Redis Configuration
redis:
  host: 'localhost'
  port: 6379
  database: 0
  max_connections: 10
  connection_timeout: 5
  ssl: false

# External APIs Configuration
external_apis:
  metaculus:
    base_url: 'https://www.metaculus.com/api2'
    timeout: 30
    rate_limit: 100

  search_providers:
    asknews:
      enabled: true
      timeout: 15
      rate_limit: 50
    perplexity:
      enabled: false
      timeout: 20
      rate_limit: 30
    exa:
      enabled: true
      timeout: 15
      rate_limit: 100
    serpapi:
      enabled: false
      timeout: 20
      rate_limit: 50
    duckduckgo:
      enabled: true
      timeout: 10
      rate_limit: 25

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_path: '/health'
  readiness_check_path: '/ready'
  log_level: 'DEBUG'
  structured_logging: true
  prometheus_enabled: false
  jaeger_enabled: false

# Security Configuration
security:
  enable_rate_limiting: false
  enable_cors: true
  cors_origins: ['*']
  enable_csrf_protection: false
  enable_input_validation: true

# Feature Flags
feature_flags:
  config_path: 'configs/feature_flags.json'
  reload_interval: 60 # 1 minute

# Performance Configuration
performance:
  enable_caching: false
  enable_compression: false
  max_concurrent_requests: 10
  enable_connection_pooling: false

# Backup Configuration
backup:
  enabled: false

# Auto-scaling Configuration
autoscaling:
  enabled: false

# Blue-Green Deployment
blue_green:
  enabled: false
