# Production Environment Configuration
environment: production

# Registry Configuration
registry:
  url: 'ghcr.io'
  namespace: 'tournament-optimization'

# Image Configuration
image:
  name: 'tournament-optimization'
  tag: 'production-latest'
  pull_policy: 'Always'

# Deployment Configuration
deployment:
  replicas: 5
  strategy: 'BlueGreen'
  max_unavailable: 0
  max_surge: 2

# Resource Configuration
resources:
  requests:
    cpu: '500m'
    memory: '1Gi'
  limits:
    cpu: '2000m'
    memory: '2Gi'

# Service Configuration
service:
  type: 'ClusterIP'
  port: 8000
  target_port: 8000

# Ingress Configuration
ingress:
  enabled: true
  host: 'tournament-optimization.example.com'
  tls: true
  tls_secret: 'tournament-optimization-production-tls'
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/rate-limit: '100'
    nginx.ingress.kubernetes.io/rate-limit-window: '1m'

# Database Configuration
database:
  host: 'tournament-optimization-prod-db.cluster-xyz.us-west-2.rds.amazonaws.com'
  port: 5432
  name: 'tournament_optimization_production'
  username: 'production_user'
  ssl_mode: 'require'
  max_connections: 50
  connection_timeout: 30
  pool_size: 20
  pool_timeout: 30
  pool_recycle: 3600

# Redis Configuration
redis:
  host: 'tournament-optimization-prod-cache.abc123.cache.amazonaws.com'
  port: 6379
  database: 0
  max_connections: 50
  connection_timeout: 5
  ssl: true
  cluster_mode: true
  sentinel_enabled: true

# External APIs Configuration
external_apis:
  metaculus:
    base_url: 'https://www.metaculus.com/api2'
    timeout: 30
    rate_limit: 500
    retry_attempts: 3
    circuit_breaker_threshold: 10

  search_providers:
    asknews:
      enabled: true
      timeout: 15
      rate_limit: 200
      priority: 1
    perplexity:
      enabled: true
      timeout: 20
      rate_limit: 100
      priority: 2
    exa:
      enabled: true
      timeout: 15
      rate_limit: 300
      priority: 3
    serpapi:
      enabled: true
      timeout: 20
      rate_limit: 200
      priority: 4
    duckduckgo:
      enabled: true
      timeout: 10
      rate_limit: 100
      priority: 5

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_path: '/health'
  readiness_check_path: '/ready'
  log_level: 'INFO'
  structured_logging: true
  prometheus_enabled: true
  jaeger_enabled: true
  distributed_tracing: true
  metrics_retention: '30d'
  log_retention: '90d'

# Security Configuration
security:
  enable_rate_limiting: true
  rate_limit_requests_per_minute: 1000
  enable_cors: true
  cors_origins: ['https://tournament-optimization.example.com']
  enable_csrf_protection: true
  enable_input_validation: true
  enable_sql_injection_protection: true
  enable_xss_protection: true
  security_headers:
    x_content_type_options: 'nosniff'
    x_frame_options: 'DENY'
    x_xss_protection: '1; mode=block'
    strict_transport_security: 'max-age=31536000; includeSubDomains'

# Feature Flags
feature_flags:
  config_path: 'configs/feature_flags.json'
  reload_interval: 300 # 5 minutes
  enable_remote_config: true
  remote_config_url: 'https://config.tournament-optimization.example.com/flags'

# Performance Configuration
performance:
  enable_caching: true
  cache_ttl: 7200 # 2 hours
  enable_compression: true
  compression_level: 6
  max_concurrent_requests: 500
  enable_connection_pooling: true
  connection_pool_size: 100
  enable_query_optimization: true
  enable_response_caching: true

# Backup Configuration
backup:
  enabled: true
  schedule: '0 1 * * *' # Daily at 1 AM
  retention_days: 90
  s3_bucket: 'tournament-optimization-production-backups'
  encryption_enabled: true
  cross_region_replication: true
  backup_verification: true

# Auto-scaling Configuration
autoscaling:
  enabled: true
  min_replicas: 5
  max_replicas: 20
  target_cpu_utilization: 60
  target_memory_utilization: 70
  scale_up_cooldown: 300
  scale_down_cooldown: 600
  custom_metrics:
    - name: 'tournament_optimization_queue_length'
      target_value: 100
    - name: 'tournament_optimization_response_time'
      target_value: 15

# Blue-Green Deployment
blue_green:
  enabled: true
  health_check_timeout: 600
  traffic_switch_delay: 120
  rollback_threshold_errors: 5
  rollback_threshold_response_time: 30
  canary_percentage: 10
  canary_duration: 300

# Disaster Recovery
disaster_recovery:
  enabled: true
  backup_frequency: 'hourly'
  cross_region_backup: true
  rto_target: 3600 # 1 hour
  rpo_target: 300 # 5 minutes
  failover_regions: ['us-east-1', 'eu-west-1']
  automated_failover: false
  manual_approval_required: true

# Circuit Breaker Configuration
circuit_breaker:
  failure_threshold: 10
  recovery_timeout: 60
  half_open_max_calls: 5
  slow_call_duration_threshold: 30
  slow_call_rate_threshold: 0.5

# Alerting Configuration
alerting:
  enabled: true
  channels:
    - type: 'slack'
      webhook_url: '${SLACK_WEBHOOK_URL}'
      severity_threshold: 'warning'
    - type: 'pagerduty'
      integration_key: '${PAGERDUTY_INTEGRATION_KEY}'
      severity_threshold: 'critical'
    - type: 'email'
      recipients: ['ops@tournament-optimization.example.com']
      severity_threshold: 'error'

# Compliance and Audit
compliance:
  audit_logging: true
  data_retention_policy: '7_years'
  gdpr_compliance: true
  sox_compliance: true
  encryption_at_rest: true
  encryption_in_transit: true
  access_logging: true
  change_tracking: true
